frontend:
    container_name: barbearia-front
    build:
      context: ./caminho-para-a-pasta-do-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./caminho-para-a-pasta-do-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development